server:
  port: 8081

spring:
  application:
    name: authentication-second

  rabbitmq:
    addresses: 192.168.112.197:5672
    username: admin
    password: Swszkj@123
    publisher-returns: true
    publisher-confirm-type: correlated
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: auto #确认模式
        prefetch: 1 #限制每次发送一条数据。
#        concurrency: 3 #同一个队列启动几个消费者
#        max-concurrency: 3 #启动消费者最大数量
#        #重试策略相关配置
#        retry:
#          # 开启消费者(程序出现异常)重试机制，默认开启并一直重试
#          enabled: true
#          # 最大重试次数
#          max-attempts: 5
#          # 重试间隔时间(毫秒)
#          initial-interval: 3000
